apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: prd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prd-app
  template:
    metadata:
      labels:
        app: prd-app
    spec:
      containers:
      - name: spring-app
        image:  gcr.io/kube-399605/product:1.0.4
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort
  selector:
    app: prd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
